name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Up Version
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ format('upVersion -Pnext={0}', github.event.inputs.version) }}

      - name: Commit Version
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: ${{ format('v{0}', github.event.inputs.version) }}

      - name: Push Tag
        uses: mathieudutour/github-tag-action@v5.5
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.version }}

      - name: Build All
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildAll

      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          draft: true
          prerelease: false
          files: |
            imgui-app/build/libs/*.jar
            imgui-binding/build/libs/*.jar
            imgui-lwjgl3/build/libs/*.jar
            bin/imgui-java64.dll
            bin/libimgui-java64.dylib
            bin/libimgui-javaarm64.dylib
            bin/libimgui-java64.so
